
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POST = 4;
  public static final int SEMICOLON = 16;
  public static final int IDENT = 11;
  public static final int RBRACE = 15;
  public static final int TEST = 2;
  public static final int STATUS = 8;
  public static final int EXPECT = 7;
  public static final int LBRACE = 14;
  public static final int PUT = 5;
  public static final int CONTAINS = 10;
  public static final int EQUALS = 17;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int NUMBER = 12;
  public static final int error = 1;
  public static final int BODY = 9;
  public static final int DELETE = 6;
  public static final int GET = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TEST",
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "EXPECT",
  "STATUS",
  "BODY",
  "CONTAINS",
  "IDENT",
  "NUMBER",
  "STRING",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "EQUALS"
  };
}

